name: Supervisely release
run-name: Supervisely ${{ github.repository }} app release
on:
  workflow_call:
    inputs:
      SUPERVISELY_SERVER_ADDRESS:
        required: true
        type: string
      SLUG:
        required: true
        type: string
      RELEASE_VERSION:
        required: true
        type: string
      RELEASE_TITLE:
        required: true
        type: string
      SUBAPP_PATHS:
        required: true
        type: string
      IGNORE_SLY_RELEASES:
        required: true
        type: string
      RELEASE_WITH_SLUG:
        required: true
        type: string
      CHECK_PREV_RELEASES:
        required: true
        type: string
    secrets:
      SUPERVISELY_API_TOKEN:
        required: true
      GH_ACCESS_TOKEN:
        required: true
      
jobs:
  Supervisely-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: supervisely-ecosystem/workflows
          path: workflow
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./workflow/requirements.txt
          pip uninstall -y urllib3 requests-toolbelt
          pip install urllib3==1.26.15 requests-toolbelt==0.10.1
      - name: Supervisely Release
        run: |
          python ./workflow/release.py $SLUG "$SUBAPP_PATHS" $IGNORE_SLY_RELEASES $RELEASE_WITH_SLUG $CHECK_PREV_RELEASES
        env:
          SERVER_ADDRESS: "${{ inputs.SUPERVISELY_SERVER_ADDRESS }}"
          API_TOKEN: "${{ secrets.SUPERVISELY_API_TOKEN }}"
          GH_ACCESS_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
          SLUG: "${{ inputs.SLUG }}"
          RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
          RELEASE_TITLE: "${{ inputs.RELEASE_TITLE }}"
          SUBAPP_PATHS: "${{ inputs.SUBAPP_PATHS }}"
          IGNORE_SLY_RELEASES: "${{ inputs.IGNORE_SLY_RELEASES }}"
          RELEASE_WITH_SLUG: "${{ inputs.RELEASE_WITH_SLUG }}"
          CHECK_PREV_RELEASES: "${{ inputs.CHECK_PREV_RELEASES }}"
